<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="traitement.php" method="post">
        <fieldset>
            <label for="fname">Nom</label><br>
            <input type="text" name="fname" id="fname"><br>
            <label for="lname">Prénoms</label><br>
            <input type="text" name="lname" id="name"><br>
            <label for="name">Mot de passe</label><br>
            <input type="password" name="mdp" id="mdp"><br>
            <label for="name">confirmation du mot de passe</label><br>
            <input type="password" name="cmdp" id="cmdp"><br>
            <input type="submit" name="inscription" id="inscription" value="S'inscrire"><br>
        </fieldset>
    </form>
</body>
</html>